### ISSUE TITLE
LV_LVGL_H_INCLUDE_SIMPLE should be changed

### ISSUE THREAD

**Issue by ZoranIT** [jakpaul/lvgl_touch_calibration#4]
I'm trying to compile this calibration with lvgl and esp_lcd_touch in eclipse. 
lvgl/lvgl.h does not exist in 8.3.9
shouldn't it be removed and changed to only lvgl.h?
I can't find a way to add LV_LVGL_H_INCLUDE_SIMPLE flag in eclipse. 

https://github.com/jakpaul/lvgl_touch_calibration/blob/7326c0b29d5bc5eb9ce1695a81096b6a735d551e/img/lv_tc_indicator_img.c#L1C1-L6C1

Thanks,

**Comment by jakpaul** [comment]
This appears to be a lvgl feature which lets you select from where the library should be included. See here: [CMake - LVGL Docs](https://docs.lvgl.io/8.3/get-started/platforms/cmake.html?highlight=lv_lvgl_h_include_simple).

The file was originally generated using the image converter tool on lvgl.io. Upon regenerating it now, some new macros have been added at the beginning of the file. If your compiler supports __has_include, it should fix the issue by defaulting to "lvgl.h" instead of "lvgl/lvgl.h" for the include path.
I made a [new branch](https://github.com/jakpaul/lvgl_touch_calibration/blob/4-lv_lvgl_h_include_simple-should-be-changed/img/lv_tc_indicator_img.c) with the changes. Feel free to test this out and let me know if it works.

**Comment by ZoranIT** [comment]
Okay, thank you. This variant compiles with eclipse, esp-idf and dependenciesover the yml file.

**Comment by jakpaul** [comment]
You're welcome. Will be merging this into master
